// <auto-generated />
using System;
using Electric.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electric.API.Migrations
{
    [DbContext(typeof(ElectricDbContext))]
    [Migration("20260730051927_ChanceFieldMeterSuplyKeyToMeterId")]
    partial class ChanceFieldMeterSuplyKeyToMeterId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Electric.API.Entities.BillEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<int>("CurrentReading")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_reading");

                    b.Property<DateTime>("CurrentReadingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_reading_date");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meter_id");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paid");

                    b.Property<int>("PreviousReading")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_reading");

                    b.Property<DateTime>("PreviousReadingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_reading_date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("Electric.API.Entities.MeterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_Id");

                    b.Property<string>("ComercialSector")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercial_sector");

                    b.Property<string>("ConsumptionType")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumption_type");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT")
                        .HasColumnName("rate");

                    b.Property<string>("SupplyKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("supply_key");

                    b.HasKey("Id");

                    b.ToTable("meters");
                });

            modelBuilder.Entity("Electric.API.Entities.BillEntity", b =>
                {
                    b.HasOne("Electric.API.Entities.MeterEntity", "Meter")
                        .WithMany("Bills")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("Electric.API.Entities.MeterEntity", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
